language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit

notifications:
  email:
    -  majermi4@gmail.com