language: php

php:
    - 5.6

before_script:
  - phpenv config-rm xdebug.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit

notifications:
  email:
    -  majermi4@gmail.com