# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:

    nimble.core.menu.builder:
        class: nimble\CoreBundle\Model\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", '%kernel.root_dir%', '@nimble.core.menu.voter', '@translator.default']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: sidebar_menu } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb_menu }

    nimble.core.menu.voter:
        class: nimble\CoreBundle\Model\Menu\MenuVoter
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.voter }

    nimble.core.menu.manipulator_extension:
        class: nimble\CoreBundle\Model\Menu\MenuManipulatorExtension
        public: false
        tags:
            - { name: twig.extension }

#    nimble.twig.globals:
#        class: nimble\CoreBundle\Twig\GlobalsExtension
#        arguments: [ "@service_container" ]
#        tags:
#            - { name: twig.extension }

    nimble.core.twig.users:
        class: nimble\CoreBundle\Twig\UsersExtension
        arguments: []
        tags:
            - { name: twig.extension }